// D-17's acceptance shape: the field-walk conformance suite that ends the
// enumerate-and-miss cycle. Three consecutive review rounds (12.3-11, 12.3-12,
// the third-pass review) each bounded whatever field its author happened to
// think of and missed the next one. This suite removes the author from the
// loop entirely: every probe below is GENERATED by walking the exported rule
// tables themselves (`Object.entries(...FIELD_RULES)`), never by a
// hand-maintained list of field names — so a field added to any of the four
// tables later is probed automatically, and a field with no rule at all fails
// `pnpm --filter applesauce-concord build` instead of reaching this suite.

import { describe, expect, it } from "vitest";
import { bytesToHex, randomBytes } from "@noble/hashes/utils.js";

import { communityId } from "../crypto.js";
import { createCommunity } from "../community.js";
import { LIST_MAX_BYTES } from "../community-list.js";
import {
  BLOB_POINTER_FIELD_RULES,
  CHANNEL_KEY_FIELD_RULES,
  HELD_KEY_FIELD_RULES,
  INVITE_BUNDLE_FIELD_RULES,
  INVITE_BUNDLE_MAX_TOTAL_BYTES,
  buildInviteBundle,
  validateInviteBundle,
  type BundleFieldRule,
} from "../invite-bundle.js";
import type { BlobPointer, ChannelKey, InviteBundle } from "../../types.js";

// ── Layer 1: a baseline fixture whose owner proof genuinely passes, with
// EVERY optional field populated, so every probe below mutates a bundle that
// would otherwise validate cleanly (TEST-01: no expected value is ever read
// back from the function under test).
const OWNER = "ab".repeat(32);
const OWNER_SALT = randomBytes(32);
const COMMUNITY_ID = bytesToHex(communityId(OWNER, OWNER_SALT));

function baselineBundle(): InviteBundle {
  return {
    community_id: COMMUNITY_ID,
    owner: OWNER,
    owner_salt: bytesToHex(OWNER_SALT),
    community_root: "cd".repeat(32),
    root_epoch: 1,
    channels: [
      {
        id: "11".repeat(32),
        key: "22".repeat(32),
        epoch: 2,
        name: "mods",
        held: [{ epoch: 1, key: "33".repeat(32) }],
      },
    ],
    relays: ["wss://relay-a.example.com", "wss://relay-b.example.com"],
    name: "Baseline Community",
    held_roots: [{ epoch: 0, key: "44".repeat(32), refounder: "55".repeat(32) }],
    refounder: "66".repeat(32),
    icon: {
      url: "https://img.example.com/a.png",
      key: "77".repeat(32),
      nonce: "nonce-value",
      hash: "88".repeat(32),
    },
    creator_npub: "99".repeat(32),
    label: "Reddit",
    expires_at: 4_000_000_000,
  };
}

/**
 * Builds a hostile value for `rule` by dispatching on `rule.kind` — never a
 * single universal literal, since a raw string is not even type-compatible
 * with every kind's positive-validity check. The `default` branch below is
 * LOAD-BEARING (D-17): it must never be softened into a skip, and a new
 * `BundleFieldRule` kind with no case here fails `tsc` via the `never`
 * assignment before it could ever reach this throw at runtime.
 */
function hostileValueFor(rule: BundleFieldRule): unknown {
  switch (rule.kind) {
    case "hex-key":
    case "bounded-text":
      return "x".repeat(60_000);
    case "safe-integer":
      // Not a safe integer — same class of failure a 60,000-char string is
      // for the string-shaped kinds above.
      return Number.MAX_SAFE_INTEGER + 100;
    case "relay-list":
    case "channel-list":
    case "held-list":
      return "not-an-array";
    case "blob-pointer":
      return "not-an-object";
    default: {
      const exhaustive: never = rule;
      throw new Error(
        `invite-bundle-schema.test.ts has no oversize probe for rule kind '${(exhaustive as BundleFieldRule).kind}' — add one; this throw is load-bearing and must never be softened into a skip (D-17)`,
      );
    }
  }
}

// ── Layer 2: generated probes, one per field of every rule table — the
// parameterisation reads Object.entries(...FIELD_RULES) directly, so there is
// no hand-maintained list of field names anywhere in this file.

describe.each(Object.entries(INVITE_BUNDLE_FIELD_RULES))("bundle field %s (generated probe)", (field, rule) => {
  it(`a malformed ${field} is handled per its declared disposition ("${rule.onInvalid}")`, () => {
    const bundle = { ...baselineBundle(), [field]: hostileValueFor(rule) };
    const result = validateInviteBundle(bundle);
    if (rule.onInvalid === "reject") {
      // A reject-disposition bundle-level field failing rejects the WHOLE bundle.
      expect(result).toBeUndefined();
    } else {
      // A drop-disposition field failing omits just that key; every other
      // field (including the owner proof) still validates.
      expect(result).toBeDefined();
      expect(Object.prototype.hasOwnProperty.call(result, field)).toBe(false);
    }
  });
});

describe.each(Object.entries(CHANNEL_KEY_FIELD_RULES))("channel-entry field %s (generated probe)", (field, rule) => {
  it(`a malformed channels[0].${field} is handled per its declared disposition — a sibling channel always survives`, () => {
    const bundle = baselineBundle();
    const poisoned = { ...(bundle.channels[0] as ChannelKey), [field]: hostileValueFor(rule) };
    const sibling: ChannelKey = { id: "99".repeat(32), key: "aa".repeat(32), epoch: 0, name: "sibling" };
    const injected = { ...bundle, channels: [poisoned, sibling] };
    const result = validateInviteBundle(injected);
    // Channel-level issues never reject the whole bundle (channel-list's
    // per-entry drop policy) — the bundle always validates here.
    expect(result).toBeDefined();
    expect(result?.channels.some((c) => c.name === "sibling")).toBe(true);
    if (rule.onInvalid === "reject") {
      // The whole poisoned ENTRY is dropped (channel-list's per-entry policy).
      expect(result?.channels.length).toBe(1);
    } else {
      // The field alone is dropped; the poisoned channel entry itself survives.
      const survivor = result?.channels.find((c) => c.id === poisoned.id);
      expect(survivor).toBeDefined();
      expect(Object.prototype.hasOwnProperty.call(survivor, field)).toBe(false);
    }
  });
});

describe.each(Object.entries(HELD_KEY_FIELD_RULES))("held-root-entry field %s (generated probe)", (field, rule) => {
  it(`a malformed held_roots[0].${field} is handled per its declared disposition ("${rule.onInvalid}")`, () => {
    const bundle = baselineBundle();
    const heldRoots = bundle.held_roots!;
    const poisoned = { ...heldRoots[0], [field]: hostileValueFor(rule) };
    const injected = { ...bundle, held_roots: [poisoned] };
    const result = validateInviteBundle(injected);
    if (rule.onInvalid === "reject") {
      // held-list rejects the WHOLE containing object on any malformed entry.
      expect(result).toBeUndefined();
    } else {
      expect(result).toBeDefined();
      const entry = result?.held_roots?.[0];
      expect(entry).toBeDefined();
      expect(Object.prototype.hasOwnProperty.call(entry, field)).toBe(false);
    }
  });
});

describe.each(Object.entries(BLOB_POINTER_FIELD_RULES))("icon field %s (generated probe)", (field) => {
  it(`a malformed icon.${field} drops the whole icon (every blob-table field is reject/reject)`, () => {
    const bundle = baselineBundle();
    const injected = { ...bundle, icon: { ...(bundle.icon as BlobPointer), [field]: hostileValueFor(BLOB_POINTER_FIELD_RULES[field as keyof BlobPointer]) } };
    const result = validateInviteBundle(injected);
    expect(result).toBeDefined();
    expect(result?.icon).toBeUndefined();
  });
});

// ── Array-kind specifics: count-cap + raw-array ordering, and the relay
// kind's per-entry length filter (in-count, one over-length entry).

describe("array-kind count-cap and ordering probes (generated over the bundle table's array fields)", () => {
  // relay-list is deliberately excluded here: its count cap SLICES the raw
  // array rather than rejecting (unchanged pre-D-17 behavior — a bundle whose
  // relays are entirely junk still validates), so it gets its own dedicated
  // truncation probe below instead of this reject-on-over-count assertion.
  const arrayFields = Object.entries(INVITE_BUNDLE_FIELD_RULES).filter(
    (entry): entry is [string, Extract<BundleFieldRule, { countCap: number }>] =>
      "countCap" in entry[1] && entry[1].kind !== "relay-list",
  );

  it.each(arrayFields)("an over-count %s array of well-formed-looking entries is refused per its disposition", (field, rule) => {
    // "Well-formed-looking" placeholder entries — the count cap must fire on
    // the RAW array length, before any per-entry validation ever runs.
    const entries = Array.from({ length: rule.countCap + 1 }, () => ({}));
    const bundle = { ...baselineBundle(), [field]: entries };
    const result = validateInviteBundle(bundle);
    expect(result).toBeUndefined();
  });

  it.each(arrayFields)(
    "the same over-count %s array with every entry malformed is refused identically (ordering guard)",
    (field, rule) => {
      const entries = Array.from({ length: rule.countCap + 1 }, () => ({ junk: true }));
      const bundle = { ...baselineBundle(), [field]: entries };
      const result = validateInviteBundle(bundle);
      // Non-vacuity: if the per-entry filter ran BEFORE the count check, every
      // entry here (all malformed) would be dropped/rejected individually,
      // potentially emptying the array below the cap — this pins the count
      // check running on the RAW array first.
      expect(result).toBeUndefined();
    },
  );
});

it("an over-count relays array is TRUNCATED to the cap, not rejected — the exception to the reject-on-over-count array kinds above", () => {
  const relayRule = INVITE_BUNDLE_FIELD_RULES.relays;
  if (relayRule.kind !== "relay-list") throw new Error("relays rule kind changed — update this probe");
  const relays = Array.from({ length: relayRule.countCap + 5 }, (_, i) => `wss://relay-${i}.example.com`);
  const result = validateInviteBundle({ ...baselineBundle(), relays });
  expect(result).toBeDefined();
  expect(result?.relays.length).toBe(relayRule.countCap);
  expect(result?.relays).toEqual(relays.slice(0, relayRule.countCap));
});

it("an in-count relays array holding one syntactically valid URL longer than the relay kind's urlMax is filtered out, not rejected", () => {
  const relayRule = INVITE_BUNDLE_FIELD_RULES.relays;
  if (relayRule.kind !== "relay-list") throw new Error("relays rule kind changed — update this probe");
  const longUrl = "wss://relay.example.com/" + "a".repeat(relayRule.urlMax);
  const bundle = { ...baselineBundle(), relays: [longUrl] };
  const result = validateInviteBundle(bundle);
  expect(result).toBeDefined();
  expect(result?.relays).toEqual([]);
});

// ── Layer 3: whole-structure invariants ──────────────────────────────────

it("no string value anywhere in a validated (maximal) bundle exceeds the largest declared cap", () => {
  const result = validateInviteBundle(baselineBundle())!;
  expect(result).toBeDefined();

  const allRules = [
    ...Object.values(INVITE_BUNDLE_FIELD_RULES),
    ...Object.values(CHANNEL_KEY_FIELD_RULES),
    ...Object.values(HELD_KEY_FIELD_RULES),
    ...Object.values(BLOB_POINTER_FIELD_RULES),
  ];
  const largestCap = Math.max(
    ...allRules.map((r) => ("max" in r ? r.max : "urlMax" in r ? r.urlMax : 0)),
  );

  const lengths: number[] = [];
  (function walk(value: unknown): void {
    if (typeof value === "string") lengths.push(value.length);
    else if (Array.isArray(value)) for (const v of value) walk(v);
    else if (value && typeof value === "object") for (const v of Object.values(value)) walk(v);
  })(result);

  expect(lengths.length).toBeGreaterThan(0);
  expect(Math.max(...lengths)).toBeLessThanOrEqual(largestCap);
});

it("every key a genuine buildInviteBundle output carries has a rule in the bundle table (builder coverage)", async () => {
  const genesis = await createCommunity({ ownerPubkey: OWNER, name: "Builder Coverage", relays: ["wss://ok.example.com"] });
  const material = {
    ...genesis.material,
    channels: [{ id: "11".repeat(32), key: "22".repeat(32), epoch: 0, name: "general" }],
    refounder: "cc".repeat(32),
  };
  const built = buildInviteBundle(material, {
    channels: ["11".repeat(32)],
    icon: { url: "https://x", key: "k", nonce: "n", hash: "h" },
    creator_npub: "dd".repeat(32),
    label: "Reddit",
    expires_at: 4_000_000_000,
  });
  for (const key of Object.keys(built)) {
    expect(Object.prototype.hasOwnProperty.call(INVITE_BUNDLE_FIELD_RULES, key)).toBe(true);
  }
  // No false negative: the genuine bundle itself validates unchanged.
  expect(validateInviteBundle(built)).toBeDefined();
});

it("the cap chain is arithmetically closed: 2x the bundle total-bytes cap fits the per-entry ceiling, and 2x that ceiling fits LIST_MAX_BYTES", () => {
  // COMMUNITY_LIST_MAX_ENTRY_BYTES is Task 3's export (community-list.ts),
  // sequenced after this task — computed here via the SAME arithmetic
  // expression (half of LIST_MAX_BYTES) rather than importing a symbol that
  // does not exist yet at this task's commit. Task 3's own suite
  // (community-list.test.ts) independently pins the real exported constant to
  // this identical expression, so the chain stays closed once Task 3 lands.
  const perEntryCeiling = Math.floor(LIST_MAX_BYTES / 2);
  expect(2 * INVITE_BUNDLE_MAX_TOTAL_BYTES).toBeLessThanOrEqual(perEntryCeiling);
  expect(2 * perEntryCeiling).toBeLessThanOrEqual(LIST_MAX_BYTES);
});
