name: Deploy Next Version
on:
  push:
    branches:
      - master

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Build typedoc
        run: pnpm typedoc

      - name: Build vitepress
        run: pnpm build --filter applesauce-docs -- --base /applesauce/

      - name: Copy vitepress
        run: cp -r packages/docs/.vitepress/dist/* docs

      - name: Deploy nsite
        run: npx -y nsite-cli upload docs --verbose --purge --privatekey ${{ secrets.NSITE_KEY }}
