name: Deploy nsite
on:
  push:
    branches:
      - next
      - master

concurrency:
  group: "nsite"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Build typedoc
        run: pnpm typedoc

      - name: Build examples
        run: VITE_BASE=/examples pnpm build --filter applesauce-examples
      - name: Copy examples
        run: mkdir -p docs/examples && cp -r apps/examples/dist/* docs/examples

      - name: Build snippets
        run: VITE_BASE=/snippets pnpm build --filter applesauce-snippets
      - name: Copy snippets
        run: mkdir -p docs/snippets && cp -r apps/snippets/dist/* docs/snippets

      - name: Build vitepress
        run: pnpm build --filter applesauce-docs

      - name: Copy vitepress
        run: cp -r apps/docs/.vitepress/dist/* docs

      - name: Build llms bundle
        run: pnpm build --filter applesauce-llms

      - name: Copy llms bundle
        run: |
          mkdir -p docs
          cp -r apps/llms/dist/. docs

      # Pushes to next deploy to the "next" build channel for testing
      - name: Deploy next version
        if: github.ref == 'refs/heads/next'
        uses: sandwichfarm/nsite-action@v0.3.1
        with:
          nbunksec: ${{ secrets.NSITE_BUNKER }}
          directory: "./docs"
          name: next

      # Pushes to master deploy the latest stable version.
      - name: Deploy release
        if: github.ref == 'refs/heads/master'
        uses: sandwichfarm/nsite-action@v0.3.1
        with:
          nbunksec: ${{ secrets.NSITE_BUNKER }}
          directory: "./docs"
